name: hifive
description: HiFive Mobile App
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.3

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.0
  change_app_package_name: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_core: ^1.24.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  font_awesome: ^5.10.1
  font_awesome_flutter: ^10.2.1
  form_inputs:
    path: packages/form_inputs
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.7.0
  pretty_dio_logger: ^1.1.1
  reactive_forms: ^14.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
